FROM python:3.10-slim AS deps

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY mpnet-base-v2/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM deps AS runtime

COPY mpnet-base-v2/app.py .

EXPOSE 8201

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8201"]
