FROM python:3.10-slim AS deps

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY minilm-l6/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM deps AS runtime

COPY minilm-l6/app.py .

EXPOSE 8200

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8200"]
