// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Read2Me.AppData;

#nullable disable

namespace Read2Me.AppData.Migrations
{
    [DbContext(typeof(Read2MeDbContext))]
    [Migration("20260623082525_RenameChunkPauseAndDropMinChunk")]
    partial class RenameChunkPauseAndDropMinChunk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Read2Me.AppData.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveLlmConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveParagraphTtsConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveTranscriptionConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveVoiceDesignConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterPauseMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkPauseMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FfmpegPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowSystemPreference")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParagraphPauseMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartPauseMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PauseMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SentenceSplitEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoiceDesignSampleText")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumePauseMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WerThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.14999999999999999);

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Read2Me.AppData.Entities.AppTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppbarBackground")
                        .HasColumnType("TEXT");

                    b.Property<string>("Background")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawerBackground")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDark")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Primary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Secondary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextPrimary")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextSecondary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("Read2Me.AppData.Entities.LlmPromptSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterPrompt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContextParagraphsAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContextParagraphsBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoicePrompt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PromptSettings");
                });

            modelBuilder.Entity("Read2Me.AppData.Entities.LlmServerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApiType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("FrequencyPenalty")
                        .HasColumnType("REAL");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PresencePenalty")
                        .HasColumnType("REAL");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopP")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LlmServerConfigs");
                });

            modelBuilder.Entity("Read2Me.AppData.Entities.ParagraphTtsServiceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParagraphTtsServiceConfigs");
                });

            modelBuilder.Entity("Read2Me.AppData.Entities.TranscriptionServiceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TranscriptionServiceConfigs");
                });

            modelBuilder.Entity("Read2Me.AppData.Entities.VoiceDesignServiceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VoiceDesignServiceConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
