// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Read2Me.Data;

#nullable disable

namespace Read2Me.Data.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260803101800_AddNarratorCharacterId")]
    partial class AddNarratorCharacterId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Read2Me.Data.Entities.AudioReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NormalizeOk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizeReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTextSnapshot")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParagraphItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transcript")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VerifyOk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerifyReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Wer")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ParagraphItemId")
                        .IsUnique();

                    b.ToTable("AudioReviews");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<Guid>("PartId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNarrator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsNarrator = true,
                            Name = "Narrator"
                        });
                });

            modelBuilder.Entity("Read2Me.Data.Entities.CharacterAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Name")
                        .IsUnique();

                    b.ToTable("CharacterAliases");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Paragraph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Paragraphs");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.ParagraphItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<Guid>("ParagraphId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceInstructions")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ParagraphId");

                    b.ToTable("ParagraphItems");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VolumeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VolumeId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(526)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NarratorCharacterId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NarratorOnlyMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Voice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignPrompt")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transcript")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TtsSettingsOverrideJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceDesignSettingsOverrideJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Voices");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.VoiceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromLevel")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FromNodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("ToLevel")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VoiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("VoiceId");

                    b.ToTable("VoiceRules");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Volume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Volumes");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.AudioReview", b =>
                {
                    b.HasOne("Read2Me.Data.Entities.ParagraphItem", "ParagraphItem")
                        .WithMany()
                        .HasForeignKey("ParagraphItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParagraphItem");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Chapter", b =>
                {
                    b.HasOne("Read2Me.Data.Entities.Part", "Part")
                        .WithMany("Chapters")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.CharacterAlias", b =>
                {
                    b.HasOne("Read2Me.Data.Entities.Character", "Character")
                        .WithMany("Aliases")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Paragraph", b =>
                {
                    b.HasOne("Read2Me.Data.Entities.Chapter", "Chapter")
                        .WithMany("Paragraphs")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.ParagraphItem", b =>
                {
                    b.HasOne("Read2Me.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId");

                    b.HasOne("Read2Me.Data.Entities.Paragraph", "Paragraph")
                        .WithMany("Items")
                        .HasForeignKey("ParagraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Paragraph");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Part", b =>
                {
                    b.HasOne("Read2Me.Data.Entities.Volume", "Volume")
                        .WithMany("Parts")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Voice", b =>
                {
                    b.HasOne("Read2Me.Data.Entities.Character", "Character")
                        .WithMany("Voices")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.VoiceRule", b =>
                {
                    b.HasOne("Read2Me.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Read2Me.Data.Entities.Voice", "Voice")
                        .WithMany()
                        .HasForeignKey("VoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Voice");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Chapter", b =>
                {
                    b.Navigation("Paragraphs");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Character", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Voices");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Paragraph", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Part", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Read2Me.Data.Entities.Volume", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
