// @ts-check
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

module.exports = defineConfig([
  // Generated by `npm run api:types` (openapi-typescript); never hand-edited, never linted.
  { ignores: ['src/app/api/schema.d.ts'] },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: ['app', 'r2m'],
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: ['app', 'r2m'],
          style: 'kebab-case',
        },
      ],
    },
  },
  {
    // The shared library wraps these Material primitives (design §7). Feature code uses
    // r2m-status-chip / ToastService instead, so the whole app restyles from one place.
    files: ['src/app/**/*.ts'],
    ignores: ['src/app/ui/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@angular/material/chips',
              message:
                'Use r2m-status-chip / r2m-speaker-chip / r2m-count-badge from @app/ui instead of raw mat-chip.',
            },
            {
              name: '@angular/material/snack-bar',
              message: 'Use ToastService from @app/ui instead of MatSnackBar.',
            },
          ],
        },
      ],
    },
  },
  {
    // HTTP goes through ApiClient / the per-area services in app/api (ticket 05), so ProblemDetails
    // mapping and the origin header happen in one place.
    files: ['src/app/**/*.ts'],
    ignores: ['src/app/api/**', 'src/app/app.config.ts', '**/*.spec.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@angular/common/http',
              message:
                'Use ApiClient or a per-area *Api service from @app/api instead of HttpClient.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {},
  },
]);
