// @ts-check
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

/**
 * Every `r2m-*` component exposes its selector as a host class (`r2m-status-chip` → `.r2m-status-chip`).
 * That class is the stable test handle the E2E suite locates by (spec D11; ticket 26): element
 * selectors and BEM classes under it never change with layout, so no `data-testid` is needed on
 * the root. The rule fails a component whose host has no `class` naming its own selector.
 */
const r2mHostClassRule = {
  meta: {
    type: 'problem',
    docs: { description: 'r2m-* components must set host.class to their selector' },
    schema: [],
    messages: {
      missing:
        "Component '{{selector}}' must declare host: { class: '{{selector}}' } — the E2E tests locate r2m-* roots by that class.",
    },
  },
  create(context) {
    const literal = (node) =>
      node && node.type === 'Literal' && typeof node.value === 'string' ? node.value : null;
    const property = (object, name) =>
      object.properties.find(
        (p) => p.type === 'Property' && p.key && (p.key.name === name || p.key.value === name),
      );
    return {
      Decorator(node) {
        const call = node.expression;
        if (call.type !== 'CallExpression' || call.callee.name !== 'Component') return;
        const meta = call.arguments[0];
        if (!meta || meta.type !== 'ObjectExpression') return;
        const selector = literal(property(meta, 'selector')?.value);
        if (!selector || !selector.startsWith('r2m-')) return;
        const host = property(meta, 'host')?.value;
        const hostClass = host && host.type === 'ObjectExpression' ? literal(property(host, 'class')?.value) : null;
        const classes = hostClass ? hostClass.split(/\s+/) : [];
        if (classes.includes(selector)) return;
        context.report({ node: meta, messageId: 'missing', data: { selector } });
      },
    };
  },
};

module.exports = defineConfig([
  // Generated by `npm run api:types` (openapi-typescript); never hand-edited, never linted.
  { ignores: ['src/app/api/schema.d.ts'] },
  {
    files: ['src/app/**/*.ts'],
    ignores: ['**/*.spec.ts'],
    plugins: { r2m: { rules: { 'host-class': r2mHostClassRule } } },
    rules: { 'r2m/host-class': 'error' },
  },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: ['app', 'r2m'],
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: ['app', 'r2m'],
          style: 'kebab-case',
        },
      ],
    },
  },
  {
    // The shared library wraps these Material primitives (design §7). Feature code uses
    // r2m-status-chip / ToastService instead, so the whole app restyles from one place.
    files: ['src/app/**/*.ts'],
    ignores: ['src/app/ui/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@angular/material/chips',
              message:
                'Use r2m-status-chip / r2m-speaker-chip / r2m-count-badge from @app/ui instead of raw mat-chip.',
            },
            {
              name: '@angular/material/snack-bar',
              message: 'Use ToastService from @app/ui instead of MatSnackBar.',
            },
          ],
        },
      ],
    },
  },
  {
    // HTTP goes through ApiClient / the per-area services in app/api (ticket 05), so ProblemDetails
    // mapping and the origin header happen in one place.
    files: ['src/app/**/*.ts'],
    ignores: ['src/app/api/**', 'src/app/app.config.ts', '**/*.spec.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@angular/common/http',
              message:
                'Use ApiClient or a per-area *Api service from @app/api instead of HttpClient.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {},
  },
]);
